 # first: type of search, 
 # second: output column number, 
 # third: label to search to be sure, 
 # fourth: max length of value there must be
 # fifth: needed for formatting with openpyxl, it is length of columns
title_label_to_search={
    "DESCRIPTION OF THE PRODUCT:":  ("not_regular", 1, '', '' , 25),
    "DESCRIPTION DU PRODUIT:":      ("not_regular", 1, '', '' , 25),
    "ОПИСАНИЕ ИЗДЕЛИЯ:":            ("not_regular", 2, '', '' , 25),
    "Name of product:":             ("regular",3, '', '' , 35),
    "Nom du produit:":              ("regular",3, '', '' , 35),
    "Наименование изделия:":        ("regular",4, '', '' , 35),
    "Lot N°:":      ("regular", 5, '', '' , 8),
    "Site:":        ("regular", 6, '', '' , 15),
    "Chantier:":    ("regular", 6, '', '' , 15),
    "Supplier:":    ("regular", 7, '', '' , 15),
    "Fournisseur:": ("regular", 7, '', '' , 15),
    "Origin:":      ("regular", 8, '', '' , 15),
    "Origine:":     ("regular", 8, '', '' , 15),
    "Place of fabrication:":    ("regular", 9, '', '' , 15),
    "Lieu de fabrication:":     ("regular", 9, '', '' , 15),
    "Localisation:":            ("regular", 10, '', '' , 35),
    "Acts:":            ("regular", 11, '', '' , 25),
    "Procès verbaux:":  ("regular", 11, '', '' , 25),
    "Протоколы:":       ("regular", 11, '', '' , 25),
    "Observations and conclusion of the controlling authority:":    ("regular", 12, '', '' , 25),
    "Observations et avis de l'organisme de contrôle:":             ("regular", 12, '', '' , 25),
    "Замечания И Заключение Тех. Надзора:":                         ("regular", 12, '', '' , 25),
    "Affaire":  ("footer", 13, "проект", 3, 8),
    "Project":  ("footer", 13, "проект", 3, 8),
    "Phase":    ("footer", 14, "зтап", 3, 8),
    "Lot":      ("footer", 15, "Pаздел", 2, 8),
    "Type":     ("footer", 16, "тип", 2, 8),
    "Zone":     ("footer", 17, "зона", 2, 8),
    "Niveau":   ("footer", 18, "зтаж", 2, 8),
    "Level":   ("footer", 18, "зтаж", 2, 8),
    "Numéro":   ("footer", 19, "номеp", 5, 8),
    "Numero":   ("footer", 19, "номеp", 5, 8),
    "Number":   ("footer", 19, "номеp", 5, 8),
    "Indice":   ("footer", 20, "Индекс", 1, 8),
    "Index":   ("footer", 20, "Индекс", 1, 8)
    }

formal_title_list=[
    "DESCRIPTION OF THE PRODUCT",
    "ОПИСАНИЕ ИЗДЕЛИЯ",
    "Name of product",
    "Наименование изделия",
    "Lot",
    "Site",
    "Supplier",
    "Origin",
    "Place of fabrication",
    "Localisation",
    "Acts",
    "Observations and conclusion of the controlling authority",
    "Affaire",
    "Phase",
    "Lot",
    "Type",
    "Zone",
    "Niveau",
    "Numéro",
    "Indice",
    "Folder Name",
    "Excel File Name",
    "Excel Sheet Name",
    "Image Name", 
    "Empty or not"
]

result_dict_for_excel={   
                1:[],
                2:[],
                3:[],
                4:[],
                5:[],
                6:[],
                7:[],
                8:[],
                9:[],
                10:[],
                11:[],
                12:[],
                13:[],
                14:[],
                15:[],
                16:[],
                17:[],
                18:[],
                19:[],
                20:[],
                21:[],
                22:[],
                23:[],
                24:[],
                25:[]
            }

print(len(result_dict_for_excel))